<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CharacterMasterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('character_masters')->insert([
            [
                'rank' => "F",
                'name' => "剣士",
                'name_id' => "swordsman",
                'hp' => 100,
                'atk' => 20,
                'speed' => 15,
                'physical_def' => 1,
                'magical_def' => 1,
                'first_weapon_id' => 1,
                'second_weapon_id' => 2,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'rank' => "F",
                'name' => "戦士",
                'name_id' => "warrior",
                'hp' => 100,
                'atk' => 25,
                'speed' => 10,
                'physical_def' => 0.9,
                'magical_def' => 1.5,
                'first_weapon_id' => 1,
                'second_weapon_id' => 3,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'rank' => "F",
                'name' => "魔法使い",
                'name_id' => "wizard",
                'hp' => 100,
                'atk' => 30,
                'speed' => 10,
                'physical_def' => 2,
                'magical_def' => 0.9,
                'first_weapon_id' => 4,
                'second_weapon_id' => 5,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'rank' => "F",
                'name' => "僧侶",
                'name_id' => "priest",
                'hp' => 100,
                'atk' => 5,
                'speed' => 10,
                'physical_def' => 0.9,
                'magical_def' => 0.9,
                'first_weapon_id' => 4,
                'second_weapon_id' => 6,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'rank' => "B",
                'name' => "聖騎士",
                'name_id' => "holy_knight",
                'hp' => 200,
                'atk' => 20,
                'speed' => 20,
                'physical_def' => 0.8,
                'magical_def' => 0.8,
                'first_weapon_id' => 2,
                'second_weapon_id' => 6,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'rank' => "B",
                'name' => "見習い魔獣使い",
                'name_id' => "elem_beast_tamer",
                'hp' => 100,
                'atk' => 15,
                'speed' => 15,
                'physical_def' => 1.2,
                'magical_def' => 1.2,
                'first_weapon_id' => 7,
                'second_weapon_id' => 8,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'rank' => "B",
                'name' => "侍",
                'name_id' => "samurai",
                'hp' => 200,
                'atk' => 30,
                'speed' => 25,
                'physical_def' => 1,
                'magical_def' => 1.3,
                'first_weapon_id' => 9,
                'second_weapon_id' => 10,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'rank' => "A",
                'name' => "上級魔獣使い",
                'name_id' => "advanced_beast_tamer",
                'hp' => 150,
                'atk' => 20,
                'speed' => 20,
                'physical_def' => 1.1,
                'magical_def' => 1.1,
                'first_weapon_id' => 11,
                'second_weapon_id' => 8,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'rank' => "A",
                'name' => "賢者",
                'name_id' => "wise_man",
                'hp' => 80,
                'atk' => 40,
                'speed' => 10,
                'physical_def' => 1,
                'magical_def' => 0.5,
                'first_weapon_id' => 12,
                'second_weapon_id' => 6,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'rank' => "S",
                'name' => "ドラゴンスレイヤー",
                'name_id' => "dragon_slayer",
                'hp' => 200,
                'atk' => 20,
                'speed' => 20,
                'physical_def' => 0.95,
                'magical_def' => 0.95,
                'first_weapon_id' => 13,
                'second_weapon_id' => 14,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'rank' => "S",
                'name' => "ドラゴン",
                'name_id' => "dragon",
                'hp' => 300,
                'atk' => 40,
                'speed' => 20,
                'physical_def' => 0.5,
                'magical_def' => 0.5,
                'first_weapon_id' => 15,
                'second_weapon_id' => 16,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
        ]);
    }
}
