<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StageInEnemySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('stage_in_enemies')->insert([
            [
                'stage_id' => 1,
                'enemy_id' => 1,
                'x' => 0,
                'y' => 0,
                'z' => 0,
                'floor' => 1,
                'is_boss' => 0,
                'atk_rate' => 1.0,
                'hp_rate' => 1.0,
                'size' => 1.0,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'stage_id' => 1,
                'enemy_id' => 1,
                'x' => 1.0,
                'y' => 3.2,
                'z' => 0,
                'floor' => 1,
                'is_boss' => 0,
                'atk_rate' => 1.0,
                'hp_rate' => 1.0,
                'size' => 1.0,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'stage_id' => 1,
                'enemy_id' => 1,
                'x' => 1.9,
                'y' => -2,
                'z' => 0,
                'floor' => 2,
                'is_boss' => 0,
                'atk_rate' => 1.05,
                'hp_rate' => 1.05,
                'size' => 1.0,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'stage_id' => 1,
                'enemy_id' => 1,
                'x' => 0,
                'y' => 0,
                'z' => 0,
                'floor' => 2,
                'is_boss' => 0,
                'atk_rate' => 1.05,
                'hp_rate' => 1.05,
                'size' => 1.05,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'stage_id' => 1,
                'enemy_id' => 1,
                'x' => 0.3,
                'y' => -0.2,
                'z' => 0,
                'floor' => 3,
                'is_boss' => 0,
                'atk_rate' => 1.1,
                'hp_rate' => 1.1,
                'size' => 1.0,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'stage_id' => 1,
                'enemy_id' => 1,
                'x' => 1,
                'y' => 2,
                'z' => 0,
                'floor' => 3,
                'is_boss' => 0,
                'atk_rate' => 1.0,
                'hp_rate' => 1.0,
                'size' => 1.5,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'stage_id' => 1,
                'enemy_id' => 2,
                'x' => 0,
                'y' => 0,
                'z' => 0,
                'floor' => 4,
                'is_boss' => 1,
                'atk_rate' => 1.0,
                'hp_rate' => 1.0,
                'size' => 2.0,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'stage_id' => 2,
                'enemy_id' => 3,
                'x' => 0,
                'y' => 0,
                'z' => 0,
                'floor' => 1,
                'is_boss' => 0,
                'atk_rate' => 1.0,
                'hp_rate' => 1.0,
                'size' => 1.0,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'stage_id' => 2,
                'enemy_id' => 3,
                'x' => 1.2,
                'y' => -2.0,
                'z' => 0,
                'floor' => 1,
                'is_boss' => 0,
                'atk_rate' => 1.0,
                'hp_rate' => 1.0,
                'size' => 1.0,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'stage_id' => 2,
                'enemy_id' => 3,
                'x' => -1.2,
                'y' => 2,
                'z' => 0,
                'floor' => 1,
                'is_boss' => 0,
                'atk_rate' => 1.0,
                'hp_rate' => 1.0,
                'size' => 1.0,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'stage_id' => 2,
                'enemy_id' => 1,
                'x' => 0.7,
                'y' => 3.5,
                'z' => 0,
                'floor' => 2,
                'is_boss' => 0,
                'atk_rate' => 1.1,
                'hp_rate' => 1.1,
                'size' => 1.1,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'stage_id' => 2,
                'enemy_id' => 1,
                'x' => -0.7,
                'y' => -2,
                'z' => 0,
                'floor' => 2,
                'is_boss' => 0,
                'atk_rate' => 1.1,
                'hp_rate' => 1.1,
                'size' => 1.1,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'stage_id' => 2,
                'enemy_id' => 3,
                'x' => 0,
                'y' => 1.5,
                'z' => 0,
                'floor' => 3,
                'is_boss' => 0,
                'atk_rate' => 1.5,
                'hp_rate' => 1.5,
                'size' => 1.5,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'stage_id' => 2,
                'enemy_id' => 3,
                'x' => 1,
                'y' => 1,
                'z' => 0,
                'floor' => 4,
                'is_boss' => 0,
                'atk_rate' => 1.2,
                'hp_rate' => 1.2,
                'size' => 1.2,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'stage_id' => 2,
                'enemy_id' => 3,
                'x' => -1,
                'y' => 1,
                'z' => 0,
                'floor' => 4,
                'is_boss' => 0,
                'atk_rate' => 1.2,
                'hp_rate' => 1.2,
                'size' => 1.0,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'stage_id' => 2,
                'enemy_id' => 4,
                'x' => 0,
                'y' => 1,
                'z' => 0,
                'floor' => 5,
                'is_boss' => 1,
                'atk_rate' => 1.0,
                'hp_rate' => 1.0,
                'size' => 2.0,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'stage_id' => 2,
                'enemy_id' => 3,
                'x' => 0,
                'y' => 4,
                'z' => 0,
                'floor' => 5,
                'is_boss' => 0,
                'atk_rate' => 1.0,
                'hp_rate' => 1.0,
                'size' => 1.0,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'stage_id' => 3,
                'enemy_id' => 5,
                'x' => 1,
                'y' => 3,
                'z' => 0,
                'floor' => 1,
                'is_boss' => 0,
                'atk_rate' => 1.0,
                'hp_rate' => 1.0,
                'size' => 1.0,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'stage_id' => 3,
                'enemy_id' => 5,
                'x' => -1,
                'y' => 3,
                'z' => 0,
                'floor' => 1,
                'is_boss' => 0,
                'atk_rate' => 1.0,
                'hp_rate' => 1.0,
                'size' => 1.0,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'stage_id' => 3,
                'enemy_id' => 5,
                'x' => 1,
                'y' => 2,
                'z' => 0,
                'floor' => 2,
                'is_boss' => 0,
                'atk_rate' => 1.1,
                'hp_rate' => 1.1,
                'size' => 1.1,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'stage_id' => 3,
                'enemy_id' => 5,
                'x' => -1,
                'y' => 2,
                'z' => 0,
                'floor' => 2,
                'is_boss' => 0,
                'atk_rate' => 1.1,
                'hp_rate' => 1.1,
                'size' => 1.1,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'stage_id' => 3,
                'enemy_id' => 5,
                'x' => 1,
                'y' => -1,
                'z' => 0,
                'floor' => 2,
                'is_boss' => 0,
                'atk_rate' => 1.1,
                'hp_rate' => 1.1,
                'size' => 1.1,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'stage_id' => 3,
                'enemy_id' => 5,
                'x' => -1,
                'y' => -1,
                'z' => 0,
                'floor' => 2,
                'is_boss' => 0,
                'atk_rate' => 1.1,
                'hp_rate' => 1.1,
                'size' => 1.1,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
            [
                'stage_id' => 3,
                'enemy_id' => 6,
                'x' => 0,
                'y' => 1,
                'z' => 0,
                'floor' => 3,
                'is_boss' => 1,
                'atk_rate' => 1.0,
                'hp_rate' => 1.0,
                'size' => 2.0,
                'created_at' => DB::raw('NOW()'),
                'updated_at' => DB::raw('NOW()'),
            ],
        ]);
    }
}
